// Builds supabase/seed/content.sql from content/*.json.
// The output is idempotent (upserts), so it can be re-run after adding content.
// Usage: npm run seed:build
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function loadContent() {
  const vocab = JSON.parse(readFileSync(join(root, 'content/vocabulary.json'), 'utf8')).words;
  const grammar = JSON.parse(readFileSync(join(root, 'content/grammar.json'), 'utf8')).topics;

  // frequency_rank = position within its level in the file
  const rankByLevel = {};
  const words = vocab.map((w) => {
    rankByLevel[w.lvl] = (rankByLevel[w.lvl] ?? 0) + 1;
    return {
      id: w.id,
      german: w.de,
      english: w.en,
      part_of_speech: w.pos,
      article: w.art ?? null,
      plural: w.pl ?? null,
      cefr_level: w.lvl,
      frequency_rank: rankByLevel[w.lvl],
      topic: w.topic,
      example_sentence: w.ex,
      example_translation: w.exEn,
      usage_note: w.note ?? null,
      grammar: w.grammar ?? [],
    };
  });

  const topics = grammar.map((t) => ({
    id: t.id,
    slug: t.slug,
    title: t.title,
    cefr_level: t.lvl,
    planned_order: t.order,
    summary: t.summary,
    content: t.lesson ?? null,
  }));

  const topicBySlug = new Map(topics.map((t) => [t.slug, t]));
  const links = [];
  for (const w of words) {
    for (const slug of w.grammar) {
      const t = topicBySlug.get(slug);
      if (!t) throw new Error(`word ${w.id} (${w.german}) links unknown grammar topic "${slug}"`);
      links.push({ word_id: w.id, topic_id: t.id });
    }
  }
  return { words, topics, links };
}

const lit = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

export function buildSql({ words, topics, links }) {
  const wordCols = ['id', 'german', 'english', 'part_of_speech', 'article', 'plural', 'cefr_level',
    'frequency_rank', 'topic', 'example_sentence', 'example_translation', 'usage_note'];
  const topicCols = ['id', 'slug', 'title', 'cefr_level', 'planned_order', 'summary', 'content'];
  const upsert = (table, cols, rows, key) =>
    `insert into public.${table} (${cols.join(', ')}) values\n` +
    rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n') +
    `\non conflict (${key}) do update set\n` +
    cols.filter((c) => c !== key).map((c) => `  ${c} = excluded.${c}`).join(',\n') + ';\n';

  return [
    '-- GENERATED by scripts/build-seed.mjs from content/*.json. Do not edit by hand.',
    '-- Idempotent: safe to run repeatedly.',
    'begin;',
    upsert('grammar_topics', topicCols, topics, 'id'),
    upsert('vocabulary_words', wordCols, words, 'id'),
    `delete from public.vocabulary_grammar_links;`,
    `insert into public.vocabulary_grammar_links (word_id, topic_id) values\n` +
      links.map((l) => `  (${l.word_id}, ${l.topic_id})`).join(',\n') + ';',
    'commit;',
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const content = loadContent();
  const out = join(root, 'supabase/seed/content.sql');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, buildSql(content));
  console.log(`wrote ${out}: ${content.words.length} words, ${content.topics.length} grammar topics, ${content.links.length} links`);
}
